### ISSUE TITLE
Model not found

### ISSUE THREAD

**Issue by JasonLinjc** [sjgosai/boda2#11]
Hi,

I'm trying to load the pre-trained model, but got this error: FileNotFoundError: [Errno 2] No such file or directory: './model_artifacts__20231222_004129__133866.tar.gz'

Thanks,
JC

**Comment by JasonLinjc** [comment]
I'm able to download gs://tewhey-public-data/CODA_resources/malinois_model__20211113_021200__287348.tar.gz, but I got this error: TypeError: BassetBranched.__init__() got an unexpected keyword argument 'criterion_reduction'

**Comment by sjgosai** [comment]
Hi, thanks for raising the issue! I'm in the process of making several non-backward compatible changes. There will be a fix in the next few weeks. Apologies for the inconvenience.

**Comment by sjgosai** [comment]
@JasonLinjc , I've updated the model artifacts and tutorial notebook to be compatible with the current version of the repo. The data can be found [here](https://storage.googleapis.com/tewhey-public-data/CODA_resources/malinois_artifacts__20211113_021200__287348.tar.gz). The tutorial notebook [load_malinois_model.ipynb](https://github.com/sjgosai/boda2/blob/main/tutorials/load_malinois_model.ipynb) has been updated. Thanks for bringing up this issue and apologies for the delay. Let me know if this doesn't resolve for you.

**Comment by sjgosai** [comment]
Please re-open if you continue to run into this error.
