### ISSUE TITLE
Acceptable data input formats

### ISSUE THREAD

**Issue by adam-dev-001** [sjgosai/boda2#12]
Hi all,

I have a datatable with just two columns: DNA sequence and activity level. Is there a way for me to input this data into the boda2 pipeline? The tutorial I see only shows how it can be done for datasets in the MPRA format.

Thanks,
Adam

**Comment by sjgosai** [comment]
Hey Adam,

If you give me a bit more info I can give you some more detailed advice, but I can try to get you started. First off, pre-split your data into three separate TSVs so you have train/validation/test batches. Building off of the notebook [construct_new_model.ipynb](tutorials/construct_new_model.ipynb), you can replace `boda.data.MPRA_DataModule` with `boda.data.SeqDataModule` ([link](https://github.com/sjgosai/boda2/blob/6addf3f6990ce0aa17fa38f4c803a4b9474ba1e8/boda/data/table_datamodule.py#L81)). 

In cell [3], replace the data_module:
```
data_module = boda.data.SeqDataModule
...
```

And in cell [4], initialize the data_module with your data files:
```
data = data_module(
    train_file = "/home/ubuntu/dummy_train.tsv",
    test_file = "/home/ubuntu/dummy_test.tsv",
    val_file = "/home/ubuntu/dummy_val.tsv",
    seq_len = 600, # Replace this based on input_len used for modeling
    left_flank = boda.common.constants.MPRA_UPSTREAM[-200:], # Replace with a string of nt from your vector
    right_flank = boda.common.constants.MPRA_DOWNSTREAM[:200], # Replace with a string of nt from your vector
    use_revcomp = True,
    skip_header=True # Use if your TSVs have a header
)
```

I'm attaching the `dummy_*.tsv` files in a zip for you to use as an example [dummy_files.zip](https://github.com/sjgosai/boda2/files/15254903/dummy_files.zip). Note is that everything in the notebook is set up to model 200nt sequences that were tested with MPRA using the reporter vector referenced in our preprint. If this isn't true for your use case, you will need to modify a few things. What immediately comes to mind is that you will want to use the `BassetVL` model_module ([link](https://github.com/sjgosai/boda2/blob/6addf3f6990ce0aa17fa38f4c803a4b9474ba1e8/boda/model/basset.py#L306)) and will need to set the options `input_len` and `n_outputs` to suitable values for your data (i.e., modify cells [3] and [5] accordingly). You will also need to alter the `seq_len` option in cell [4] to match `input_len` option in cell [5]. Keep in mind is that the Basset architecture, generally, has a requirement that `input_len` = (n * 48) - 24, where n is an integer. This means you will likely need to provide the data_module with nucleotide sequences to serve as left and right flanks using the `left_flank` and `right_flank` options in cell [4].

Hope this gets you started.
