### ISSUE TITLE
Error in training due to pytorch-lightning version

### ISSUE THREAD

**Issue by yxwvutt** [sjgosai/boda2#8]
Hi, I recently tried running your construct_new_model.ipynb notebook and encountered an error with the pytorch-lightning version having some of your training modules deprecated after version 2.0. Could you all please provide the lightning.pytorch used in this paper in the requirements.txt file?

**Comment by sjgosai** [comment]
Thanks for the heads up. The version of pytorch-lightning I'm using is `1.9.5`.
