### ISSUE TITLE
Error in example implementation of sequence generation.

### ISSUE THREAD

**Issue by yxwvutt** [sjgosai/boda2#9]
Hi there, I recently attempted your implementation of generation using the tutorial command, below is exactly what I used:
```
python src/generate.py \
  --params_module StraightThroughParameters \
    --n_channels 4 --length 200 --n_samples 10 \
  --energy_module OverMaxEnergy \
    --model_artifact tmp/test_new_config/model_artifacts__20231127_235004__284796.tar.gz \
    --bias_cell 0 --bending_factor 1.0 --a_min -2.0 --a_max 6.0 \
  --generator_module FastSeqProp \
    --energy_threshold -2.0 --max_attempts 20 --n_steps 200 \
    --n_proposals 20 \
  --proposal_path tmp/generated/
```
The model training worked fine and I was able to get pretty close to what the preprint's pearson correlations, however the generate command as given does not seem to work. Below is a snippet of the error I get:
```
File "/opt/py/conda/PyLib_Common/envs/boda2/lib/python3.10/site-packages/boda-0.2.0-py3.10.egg/boda/generator/FastSeqProp.py", line 230, in generate
    states    = torch.cat([states,     final_states[energy_filter].cpu()], dim=0)
RuntimeError: Tensors must have same number of dimensions: got 3 and 4
```
Would you know why this may be the case? I have tried several different parameter combinations and have never gotten FastSeqProp to work. I have gotten Simulated Annealing to work fine.

Also, there seems to be no add_generator_specific_args function in AdaLead.py even though there is one in the SimulatedAnnealing and FastSeqProp class. Therefore, AdaLead also does not work. Is there a reason why this is the case?

**Comment by sjgosai** [comment]
Thanks for flagging this. I'll try to get to the bottom of this error for FastSeqProp and fix AdaLead.
